# Generated by Django 4.1.7 on 2023-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_obras_data_inicio_alter_obras_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='img',
            field=models.FileField(upload_to='img'),
        ),
    ]
