# Generated by Django 4.1.7 on 2023-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imagem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='ADM',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='Layout',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='SPDA',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='SPT',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='TUE',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='TUG',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='agua_fria',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='agua_quente',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='alimentacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='argamassa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='asfalto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='biodigestores',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='caderno_tecnico',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='caixa_dagua',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='ceramica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='checklist_visita_tecnica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='chumbadores',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='complementos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='compras',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='comunicacao_visual',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='construtora_cliente',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='construtora_fornecedores',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='construtora_terceiros',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='contencoes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='contratacoes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='corpo_de_prova',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='cortes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='dados',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='drenagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='esgoto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='execucao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fachada',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='ficha_verificacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='financeiro',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='financeiro1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fisico',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fisico1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fisico_financeiro',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fisico_financeiro1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='fotos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='gas',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='historico_compras',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='iluminacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='impermeabilizacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='implantacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='incendio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='indicador_produtividade',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='informacoes_contato',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='infraestrutura',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='infraestrutura_eletrica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='instrucao_tecnica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='jardinagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='locacao_de_infraestrurura',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='logistica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='memorial_calculo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='memorial_descritivo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='notificacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='paginacao_de_piso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='pavimentacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='piscina',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='plano_acao_macro',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='plano_acao_micro',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='planta_baixa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='planta_de_cobertura',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='pluvial',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='pos_venda',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='pre_venda',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='previsao_tempo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='quantitativos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='ramais_agua_fria',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='ramais_ar_pressurizado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='ramais_esgoto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='reboco',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='reuso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='romaneio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='solicitacao_compras',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='status_compras',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='superestrutura',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='tabela_de_preco',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='termos_garantia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='teste_continuidade',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='uso_terreno',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='videos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='vizinhanca',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='cep',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='imagens',
            field=models.ManyToManyField(blank=True, null=True, to='app.imagem'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
