# Generated by Django 4.1.7 on 2023-05-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_obras_adm_obras_layout_obras_spda_obras_spt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.URLField(blank=True, null=True)),
                ('planta_data', models.DateField(blank=True, null=True)),
                ('imagens', models.ManyToManyField(blank=True, null=True, to='app.imagem')),
            ],
        ),
    ]
