# Generated by Django 4.1.7 on 2023-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='imagens',
        ),
        migrations.AddField(
            model_name='planta',
            name='imagens',
            field=models.FileField(default=1, upload_to='planta'),
            preserve_default=False,
        ),
    ]
