# Generated by Django 4.1.7 on 2023-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_planta_planta_planta_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='planta_baixa',
        ),
        migrations.AddField(
            model_name='obras',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='planta_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='obras',
            name='imagens',
        ),
        migrations.AddField(
            model_name='obras',
            name='imagens',
            field=models.FileField(default=1, upload_to='planta'),
            preserve_default=False,
        ),
    ]
