# Generated by Django 4.1.7 on 2023-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_obras_descricao_remove_obras_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='descricao_planta_baixa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='imagem_planta_baixa',
            field=models.FileField(default=1, upload_to='planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obras',
            name='planta_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Arquitetonico',
        ),
    ]
