# Generated by Django 4.1.7 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_obras_descricao_planta_baixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='imagem_planta_baixa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
