# Generated by Django 4.1.7 on 2023-05-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_obras_imagem_planta_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='descricao_planta_baixa1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
