# Generated by Django 4.1.7 on 2023-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_obras_descricao_planta_baixa1'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='imagem_planta_baixa1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='obras',
            name='planta_data1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
