# Generated by Django 4.1.7 on 2023-07-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_obras_imagem_planta_baixa1_obras_planta_data1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='imagem_planta_baixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.imagem'),
        ),
    ]
