# Generated by Django 4.1.7 on 2023-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_obras_imagem_planta_baixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='descricao_planta_baixa',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='descricao_planta_baixa1',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='imagem_planta_baixa1',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='planta_data',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='planta_data1',
        ),
        migrations.AddField(
            model_name='imagem',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagem',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
