# Generated by Django 4.1.7 on 2023-08-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_obras_descricao_planta_baixa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='imagem_planta_baixa',
        ),
        migrations.AddField(
            model_name='imagem',
            name='obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.obras'),
            preserve_default=False,
        ),
    ]
