# Generated by Django 4.1.7 on 2023-08-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_obras_imagem_planta_baixa_imagem_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras'),
        ),
    ]
