# Generated by Django 4.1.7 on 2023-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_imagem_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='img1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
