# Generated by Django 4.1.7 on 2023-08-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_imagem_img1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='img',
        ),
    ]
