# Generated by Django 4.1.7 on 2023-08-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_imagem_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='img1',
            new_name='imagem',
        ),
    ]
