# Generated by Django 4.1.7 on 2023-08-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
