# Generated by Django 4.1.7 on 2023-08-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_imagecortes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTUG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTabelaprecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSuperestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSol_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageReuso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageReboco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRamal_ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRamal_agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageQuantitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrevenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePosvenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePluvial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePlanomicro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePlanomacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePiscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Imagepcobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePavimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePaginacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageNotificacoesatrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMemorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Imagemd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLocinfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInstrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfrahidra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfcontato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageIncendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageImplantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageImpermeab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageIluminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFisicofinanc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFachada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageEsgoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDrenagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Imagecp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageContratacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageContinuidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageContencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageConstrutoraforn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageConstrutoracliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageConstrutora3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageComplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChumbadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCeramica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCaderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBiodigestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsfalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageArgamassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAguaquente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAguafria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras')),
            ],
        ),
    ]
